### ISSUE TITLE
Crashing 

### ISSUE THREAD

**Issue by TheButterbrotMan** [LXGaming/NorthernCompass#6]
https://bytebin.lucko.me/VfZZjGIIGO

**Comment by LXGaming** [comment]
Interesting, Are you playing a modpack? If so can you link it.

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by LXGaming** [comment]
Blame [Luligabi1/MagicFungi](https://github.com/Luligabi1/MagicFungi), They are causing the `ItemProperties` class to be loaded while the `Items` class is still in the process of loading which is resulting in null Items being passed to `ItemProperties.register`.

This behavior would explain this issue: https://github.com/Luligabi1/MagicFungi/issues/51

## Technical Information

#### NorthernCompass Mod Only
```
[17:23:28] [Render thread/INFO]: ItemProperties.register:
[17:23:28] [Render thread/INFO]:  - Item: compass, Class: net.minecraft.class_1759
[17:23:28] [Render thread/INFO]:  - Resource: minecraft:angle, Class: net.minecraft.class_2960
[17:23:28] [Render thread/INFO]:  - Property: net.minecraft.class_5272$2@5686f018, Class: net.minecraft.class_5272$2
[17:23:28] [Render thread/INFO]: ItemProperties.<clinit>
java.lang.Exception: null
	at net.minecraft.class_5272.handler$zza000$onInit(class_5272.java:1039) ~[client-intermediary.jar:?]
	at net.minecraft.class_5272.<clinit>(class_5272.java:289) ~[client-intermediary.jar:?]
	at io.github.lxgaming.northerncompass.fabric.FabricMod.onInitializeClient(FabricMod.java:31) ~[NorthernCompass-Fabric-1.18.2-1.0.11.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.13.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:452) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

#### Deathdusk Modpack
```
[17:25:36] [main/INFO]: ItemProperties.register:
[17:25:36] [main/INFO]:  - Item: null, Class: null
[17:25:36] [main/INFO]:  - Resource: minecraft:angle, Class: net.minecraft.class_2960
[17:25:36] [main/INFO]:  - Property: net.minecraft.class_5272$2@2e059f8d, Class: net.minecraft.class_5272$2
[17:25:36] [main/INFO]: ItemProperties.<clinit>
java.lang.Exception: null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at net.minecraft.client.item.ModelPredicateProviderRegistry.handler$hmm002$onInit(ModelPredicateProviderRegistry:2539) ~[?:?]
	at net.minecraft.client.item.ModelPredicateProviderRegistry.<clinit>(ModelPredicateProviderRegistry:289) ~[?:?]
	at net.fabricmc.fabric.mixin.object.builder.ModelPredicateProviderRegistryAccessor.callRegister(ModelPredicateProviderRegistryAccessor.java) ~[fabric-object-builder-api-v1-2.0+40c91ec860-692cd366897f99bd.jar:?]
	at net.fabricmc.fabric.api.object.builder.v1.client.model.FabricModelPredicateProviderRegistry.register(FabricModelPredicateProviderRegistry.java:45) ~[fabric-object-builder-api-v1-2.0+40c91ec860-692cd366897f99bd.jar:?]
	at com.github.crimsondawn45.fabricshieldlib.lib.object.FabricBannerShieldItem.<init>(FabricBannerShieldItem.java:59) ~[FabricShieldLib-1.5.3-1.18.jar:?]
	at me.luligabi.magicfungi.common.item.tool.ClypeusShieldItem.<init>(ClypeusShieldItem.java:10) ~[magicfungi-0.7.1-BETA+1.18.2.jar:?]
	at me.luligabi.magicfungi.common.item.ItemRegistry.<clinit>(ItemRegistry.java:68) ~[magicfungi-0.7.1-BETA+1.18.2.jar:?]
	at net.minecraft.item.ArmorItem.handler$gnj001$constructor(ArmorItem:2538) ~[?:?]
	at net.minecraft.item.ArmorItem.<init>(ArmorItem:95) ~[?:?]
	at dqu.additionaladditions.registry.AdditionalMaterials.<clinit>(AdditionalMaterials.java:18) ~[AdditionalAdditions-3.0.1.jar:?]
	at net.minecraft.item.ArmorItem.handler$zzd000$constructor(ArmorItem:532) ~[?:?]
	at net.minecraft.item.ArmorItem.<init>(ArmorItem:95) ~[?:?]
	at net.minecraft.item.Items.<clinit>(Items:731) ~[?:?]
	at net.minecraft.util.registry.Registry.method_10234(Registry:192) ~[?:?]
	at net.minecraft.util.registry.Registry.method_40280(Registry:352) ~[?:?]
	at net.minecraft.util.registry.Registry.method_34031(Registry:300) ~[?:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry:299) ~[?:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap:49) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:153) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

**Comment by Luligabi1** [comment]
Hey, I've tracked this issue down to Fabric Shield Lib, one of the libs bundled with Magic Fungi. I've opened an issue for this glitch on their repository, which you can track here: CrimsonDawn45/Fabric-Shield-Lib#85
